name: Check links

on:
  push:
    branches:
      - check-links
  schedule:
    # every week
    - cron: "0 0 */7 * 1"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - name: install dependencies
        run: |
          cd $GITHUB_WORKSPACE/newbepro
          npm ci
      - name: run check-links
        run: |
          cd $GITHUB_WORKSPACE/newbepro
          echo {} > db.json & npx hexo check-links
